config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :cities
  root to: "cities#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  attr_accessor :distance

  validates :longitude, :latitude, numericality: true
  validates :country, :capital, presence: true

  def keywords
    [self.capital, self.country].compact
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  include TravelRange::GreatCircle

  def index
    @cities = load_cities

    respond_to do |format|
      format.html
      format.json { render json: CitySerializer.new(@cities).serializable_hash }
    end
  end

  private
  def search_params
    params.delete(:commit)
    params.permit(:lat, :lon, :radius)
  end

  ##
  # Load cities
  def load_cities
    return [] unless %i(lat lon radius).all? { |p| search_params[p].present? }

    lat = search_params[:lat].to_d
    lon = search_params[:lon].to_d
    radius = search_params[:radius].to_d

    distance = Distance.new(lat, lon)

    City.all.select { |city|
      city_distance = distance.compute(city.latitude, city.longitude, Unit::KILOMETER)
      in_range = city_distance <= radius
      city.distance = city_distance if in_range
      in_range
    }.sort_by(&:distance)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/index.html.haml
.py-12
  .flex.justify-center
    = form_with url: cities_path, method: :get do |f|
      .grid.grid-cols-1.gap-6
        %label.block
          %span.text-gray-700
            Latitude
          = f.number_field :lat,
            value: params[:lat],
            id: 'form-latitude',
            step: :any,
            placeholder: '48.67915',
            class: 'mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50'

        %label.block
          %span.text-gray-700
            Longitude
          = f.number_field :lon,
            value: params[:lon],
            id: 'form-longitude',
            step: :any,
            placeholder: '7.51224',
            class: 'mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50'

        %label.block
          %span.text-gray-700
            Radius (Kms)
          = f.number_field :radius,
            value: params[:radius],
            id: 'form-radius',
            placeholder: '300',
            class: 'mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50'

        = f.submit 'Submit',
          id: 'form-submit',
          class: 'justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500'

- if @cities.any?
  .py-12
    .mt-8
      .cities
        .grid.grid-cols-3.gap-6
          - @cities.each do |city|
            .city.max-w-xs.mx-auto.overflow-hidden.bg-white.rounded-lg.shadow-lg.dark:bg-gray-800
              = image_tag Faker::LoremFlickr.image(size: "500x500", search_terms: city.keywords), class: "object-cover w-full h-56"
              .py-5.text-center
                %span.capital.block.text-2xl.font-bold.text-gray-800.dark:text-white
                  = city.capital
                %span.country.block.text-sm.text-gray-700.dark:text-gray-200
                  = city.country
                %span.kilometers.block.text-sm.text-gray-400.dark:text-gray-200
                  = number_with_precision(city.distance, precision: 2)
                  kms


:javascript
  $(document).ready(function() {
    if(navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(position => {
        var lat = $('#form-latitude')
        if (!lat.val()) {
          lat.val(position.coords.latitude);
        }

        var lon = $('#form-longitude')
        if (!lon.val()) {
          lon.val(position.coords.longitude);
        }
      });
    }
  })

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TravelRange
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    .antialiased.text-gray-900.px-6
      .max-w-xl.mx-auto.py-12.divide-y.md:max-w-4xl
        .py-8
          %h1.text-4xl.font-bold
            Travel Range

        = yield